from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENTRY = ROOT / "app" / "runtime_entry.py"
MARKER = "# NEXUS_AUTHORING_STUDIO_V3"


def main() -> None:
    source = ENTRY.read_text(encoding="utf-8")
    # Remove prior authoring registrations generated by older build scripts.
    source = source.replace(
        "\n\n# NEXUS_AUTHORING_STUDIO_V2\nfrom app.admin_authoring import register_authoring\nregister_authoring(app)\n",
        "\n",
    )
    if MARKER not in source:
        source = source.rstrip() + (
            "\n\n# NEXUS_AUTHORING_STUDIO_V3\n"
            "from app.admin_authoring_v3 import register_authoring_v3\n"
            "register_authoring_v3(app)\n"
        )
    ENTRY.write_text(source, encoding="utf-8")
    print("NEXUS Course Studio V3 registrado directamente.")


if __name__ == "__main__":
    main()
